apiVersion: v1
kind: ConfigMap
metadata:
  name: social.network
  namespace: skillbox-40
data:
  application.yml: |-

    spring:
      liquibase:
        enabled: false
        drop-first: false
        change-log: classpath:database-social.network-changelog.xml
      kafka:
        bootstrap-service: ${KAFKA_HOST}:9092

      datasource:
        url: jdbc:postgresql://postgres:5432/social
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
          minimum-idle: 10
          maximum-pool-size: 50

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            default_schema: social.network
        open-in-view: false

