apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: skillbox-40
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels: 
        app: kafka
    spec:
      containers:
        - name: kafka
          image: skillboxgroup40/kafka:0.0.1
          #ports:
          #  - containerPort: 9092
          #     key: username
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: skillbox-40
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30052
  type: LoadBalancer