kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: skillbox-40
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps", "v1"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets", "deployment"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: skillbox-40
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""