package ru.skillbox.diplom.group40.social.network.api.dto.notification;

public enum Type {
    LIKE, POST, POST_COMMENT, COMMENT_COMMENT, MESSAGE, FRIEND_REQUEST, FRIEND_BIRTHDAY, SEND_EMAIL_MESSAGE,
    FRIEND_APPROVE, FRIEND_BLOCKED, FRIEND_UNBLOCKED, FRIEND_SUBSCRIBE, USER_BIRTHDAY
}
